# Use the CU AESD Docker-in-Docker image as the base environment
FROM cuaesd/aesd-autotest:latest

# [Optional] Install any additional packages you may need for your assignments
# RUN apt-get update && apt-get install -y <your-package-list>

# Ensure the default system shell is bash
ENV SHELL=/bin/bash